name: Build and deploy project to vercel on PR to main
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created, edited]

jobs:
  build:
    if: >
      (github.event_name == 'pull_request' && 
      github.event.pull_request.base.ref == 'main') ||
      (github.event_name == 'issue_comment' &&
      github.event.pull_request.base.ref == 'main' &&
      contains(github.event.comment.body, 'run build'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo in VM
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v4
      - name: Install npm and build
        # | operator treats each everything follows as a multi-line literal block
        run: |
          npm i
          npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Vite Build artifacts
          path: dist/
  spin-up-vercel-app:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the repo in VM
        uses: actions/checkout@v3
      - name: Check if file exists
        continue-on-error: true
        run: |
          cd dist
          ls
      - name: Download build artifact
        uses: actions/download-artifact@v5
        with:
          name: Vite Build artifacts
          path: dist
      - name: Check if file exists
        continue-on-error: true
        run: |
          cd dist
          ls
